//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NssIT.Kiosk.PaymentGatewaySchedule.SecurityProperty {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SecureCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SecureCode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NssIT.Kiosk.PaymentGatewaySchedule.SecurityProperty.SecureCode", typeof(SecureCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 77BB49EB60E241AC85D108400C38AA6C.
        /// </summary>
        internal static string HashSecretKeyDEV {
            get {
                return ResourceManager.GetString("HashSecretKeyDEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 43E7F2C88A824F9BA27C927CACE2D08F.
        /// </summary>
        internal static string HashSecretKeyLIVE {
            get {
                return ResourceManager.GetString("HashSecretKeyLIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paymentgateway.nssit.com.my.
        /// </summary>
        internal static string LIVE_DomainUrl {
            get {
                return ResourceManager.GetString("LIVE_DomainUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6131396BC88E43F2B8538FDB60331C7C.
        /// </summary>
        internal static string TVMKeyDEV {
            get {
                return ResourceManager.GetString("TVMKeyDEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1DD523D4D26A481F923407086C428AF7.
        /// </summary>
        internal static string TVMKeyLIVE {
            get {
                return ResourceManager.GetString("TVMKeyLIVE", resourceCulture);
            }
        }
    }
}
